apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadahie1588-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadahie1588-tenant-component
    app.kubernetes.io/part-of: loadahie1588-tenant-app
  name: loadahie1588-tenant-component
  namespace: loadahie1588-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadahie1588-tenant-component
    weight: null
status: {}
